Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/impish64"

  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "private_network", ip: "192.168.30.21"

  config.vm.synced_folder "./", "/var/www", create: true, group: "www-data", owner: "www-data"

  config.vm.provision "shell" do |s|
    s.path = "bootstrap.sh"
  end
  
end